### ISSUE TITLE
Failure on starting KF with installed security manager in readonly mode

### ISSUE THREAD

**Issue by janste63** [knopflerfish/knopflerfish.org#1]
This is copied from sourceforge #186:

If I run knopflerfish with installed security manager with option org.knopflerfish.framework.readonly=true
- without creating empty directories fwdir/perms and fwdir/condperm knopflerfisch fails with exception

java.lang.NullPointerException
        at org.knopflerfish.framework.permissions.PermUtil.getSortedFiles(PermUtil.java:134)
        at org.knopflerfish.framework.permissions.PermissionInfoStorage.load(PermissionInfoStorage.java:316)
        at org.knopflerfish.framework.permissions.PermissionInfoStorage.<init>(PermissionInfoStorage.java:94)
        at org.knopflerfish.framework.permissions.PermissionsHandle.<init>(PermissionsHandle.java:68)
        at org.knopflerfish.framework.SecurePermissionOps.init(SecurePermissionOps.java:124)
        at org.knopflerfish.framework.FrameworkContext.init(FrameworkContext.java:303)
        at org.knopflerfish.framework.SystemBundle.doInit(SystemBundle.java:618)
        at org.knopflerfish.framework.SystemBundle.init(SystemBundle.java:152)
        at org.knopflerfish.framework.Main.assertFramework(Main.java:445)
        at org.knopflerfish.framework.Main.handleArgs(Main.java:541)
        at org.knopflerfish.framework.Main.start(Main.java:224)
        at org.knopflerfish.framework.Main.main(Main.java:153)
        at org.freeplane.launcher.Launcher.run(Launcher.java:90)
        at org.freeplane.launcher.Launcher.launch(Launcher.java:56)
        at org.freeplane.launcher.Launcher.main(Launcher.java:49)
because it wants to get (empty) list of files from directories which are not created.
There is a workaround to create the directories before the application run.
I think if were nice if Knopflerfish could accept the case of missing directories.

**Comment by janste63** [comment]
Fixed NPE in framework 7.2.3, see commit  [https://github.com/knopflerfish/knopflerfish.org/commit/ff725ef6d61f260afb0130ad3fdd97721969c535]
