### ISSUE TITLE
StackOverflowError when using JAXRS publisher

### ISSUE THREAD

**Issue by chlarsson** [knopflerfish/knopflerfish.org#14]
A StackOverflowError is created when using the JAXRS Publisher bundle in combination with KF's SCR.

Code getting/ungetting service is:
@Override
  public Object addingService( ServiceReference reference ) {
    Object service = context.getService( reference );
    return delegateAddService( reference, service );
  }

  private Object delegateAddService( ServiceReference reference, Object service ) {
    Object result;
    if( isResource( service ) ) {
      result = connector.addResource( reference );
    } else {
      context.ungetService( reference );
      result = null;
    }
    return result;
}

The JAXRS code can be found at:
https://github.com/hstaudacher/osgi-jax-rs-connector

Loop is below. 
at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.delegateAddService(ResourceTracker.java:48)
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:40)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
	at org.knopflerfish.framework.Listeners.serviceChanged(Listeners.java:430)
	at org.knopflerfish.framework.PermissionOps.callServiceChanged(PermissionOps.java:340)
	at org.knopflerfish.framework.Services.register(Services.java:179)
	at org.knopflerfish.framework.BundleContextImpl.registerService(BundleContextImpl.java:274)
	at org.knopflerfish.bundle.component.ComponentConfiguration.registerService(ComponentConfiguration.java:341)
	at org.knopflerfish.bundle.component.DelayedComponent.activateComponentConfiguration(DelayedComponent.java:60)
	at org.knopflerfish.bundle.component.Component.satisfied(Component.java:492)
	at org.knopflerfish.bundle.component.Component.removeComponentConfiguration(Component.java:835)
	at org.knopflerfish.bundle.component.ComponentConfiguration.remove(ComponentConfiguration.java:596)
	at org.knopflerfish.bundle.component.ComponentConfiguration.deactivate(ComponentConfiguration.java:236)
	at org.knopflerfish.bundle.component.ComponentConfiguration.ungetService(ComponentConfiguration.java:537)
	at org.knopflerfish.framework.PermissionOps.callUngetService(PermissionOps.java:370)
	at org.knopflerfish.framework.ServiceRegistrationImpl.ungetService(ServiceRegistrationImpl.java:551)
	at org.knopflerfish.framework.ServiceReferenceImpl.ungetService(ServiceReferenceImpl.java:220)
	at org.knopflerfish.framework.BundleContextImpl.ungetService(BundleContextImpl.java:406)
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.delegateAddService(ResourceTracker.java:48)
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:40)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
	at org.knopflerfish.framework.Listeners.serviceChanged(Listeners.java:430)
	at org.knopflerfish.framework.PermissionOps.callServiceChanged(PermissionOps.java:340)
	at org.knopflerfish.framework.Services.register(Services.java:179)
	at org.knopflerfish.framework.BundleContextImpl.registerService(BundleContextImpl.java:274)
	at org.knopflerfish.bundle.component.ComponentConfiguration.registerService(ComponentConfiguration.java:341)
	at org.knopflerfish.bundle.component.DelayedComponent.activateComponentConfiguration(DelayedComponent.java:60)
	at org.knopflerfish.bundle.component.Component.satisfied(Component.java:492)
	at org.knopflerfish.bundle.component.Component.removeComponentConfiguration(Component.java:835)
	at org.knopflerfish.bundle.component.ComponentConfiguration.remove(ComponentConfiguration.java:596)
	at org.knopflerfish.bundle.component.ComponentConfiguration.deactivate(ComponentConfiguration.java:236)
	at org.knopflerfish.bundle.component.ComponentConfiguration.ungetService(ComponentConfiguration.java:537)
	at org.knopflerfish.framework.PermissionOps.callUngetService(PermissionOps.java:370)
	at org.knopflerfish.framework.ServiceRegistrationImpl.ungetService(ServiceRegistrationImpl.java:551)
	at org.knopflerfish.framework.ServiceReferenceImpl.ungetService(ServiceReferenceImpl.java:220)
	at org.knopflerfish.framework.BundleContextImpl.ungetService(BundleContextImpl.java:406)
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.delegateAddService(ResourceTracker.java:48)
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:40)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
	at org.knopflerfish.framework.Listeners.serviceChanged(Listeners.java:430)
	at org.knopflerfish.framework.PermissionOps.callServiceChanged(PermissionOps.java:340)
	at org.knopflerfish.framework.Services.register(Services.java:179)
	at org.knopflerfish.framework.BundleContextImpl.registerService(BundleContextImpl.java:274)
	at org.knopflerfish.bundle.component.ComponentConfiguration.registerService(ComponentConfiguration.java:341)
	at org.knopflerfish.bundle.component.DelayedComponent.activateComponentConfiguration(DelayedComponent.java:60)
	at org.knopflerfish.bundle.component.Component.satisfied(Component.java:492)
	at org.knopflerfish.bundle.component.Component.removeComponentConfiguration(Component.java:835)
	at org.knopflerfish.bundle.component.ComponentConfiguration.remove(ComponentConfiguration.java:596)
	at org.knopflerfish.bundle.component.ComponentConfiguration.deactivate(ComponentConfiguration.java:236)
	at org.knopflerfish.bundle.component.ComponentConfiguration.ungetService(ComponentConfiguration.java:537)
	at org.knopflerfish.framework.PermissionOps.callUngetService(PermissionOps.java:370)
	at org.knopflerfish.framework.ServiceRegistrationImpl.ungetService(ServiceRegistrationImpl.java:551)
	at org.knopflerfish.framework.ServiceReferenceImpl.ungetService(ServiceReferenceImpl.java:220)
	at org.knopflerfish.framework.BundleContextImpl.ungetService(BundleContextImpl.java:406)
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.delegateAddService(ResourceTracker.java:48)
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:40)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
	at org.knopflerfish.framework.Listeners.serviceChanged(Listeners.java:430)
	at org.knopflerfish.framework.PermissionOps.callServiceChanged(PermissionOps.java:340)
	at org.knopflerfish.framework.Services.register(Services.java:179)
	at org.knopflerfish.framework.BundleContextImpl.registerService(BundleContextImpl.java:274)
	at org.knopflerfish.bundle.component.ComponentConfiguration.registerService(ComponentConfiguration.java:341)
	at org.knopflerfish.bundle.component.DelayedComponent.activateComponentConfiguration(DelayedComponent.java:60)
	at org.knopflerfish.bundle.component.Component.satisfied(Component.java:492)
	at org.knopflerfish.bundle.component.Component.removeComponentConfiguration(Component.java:835)
	at org.knopflerfish.bundle.component.ComponentConfiguration.remove(ComponentConfiguration.java:596)
	at org.knopflerfish.bundle.component.ComponentConfiguration.deactivate(ComponentConfiguration.java:236)
	at org.knopflerfish.bundle.component.ComponentConfiguration.ungetService(ComponentConfiguration.java:537)
	at org.knopflerfish.framework.PermissionOps.callUngetService(PermissionOps.java:370)
	at org.knopflerfish.framework.ServiceRegistrationImpl.ungetService(ServiceRegistrationImpl.java:551)
	at org.knopflerfish.framework.ServiceReferenceImpl.ungetService(ServiceReferenceImpl.java:220)
	at org.knopflerfish.framework.BundleContextImpl.ungetService(BundleContextImpl.java:406)
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.delegateAddService(ResourceTracker.java:48)
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:40)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
	at org.knopflerfish.framework.Listeners.serviceChanged(Listeners.java:430)
	at org.knopflerfish.framework.PermissionOps.callServiceChanged(PermissionOps.java:340)
	at org.knopflerfish.framework.Services.register(Services.java:179)
	at org.knopflerfish.framework.BundleContextImpl.registerService(BundleContextImpl.java:274)
	at org.knopflerfish.bundle.component.ComponentConfiguration.registerService(ComponentConfiguration.java:341)
	at org.knopflerfish.bundle.component.DelayedComponent.activateComponentConfiguration(DelayedComponent.java:60)
	at org.knopflerfish.bundle.component.Component.satisfied(Component.java:492)
	at org.knopflerfish.bundle.component.Component.removeComponentConfiguration(Component.java:835)
	at org.knopflerfish.bundle.component.ComponentConfiguration.remove(ComponentConfiguration.java:596)
	at org.knopflerfish.bundle.component.ComponentConfiguration.deactivate(ComponentConfiguration.java:236)
	at org.knopflerfish.bundle.component.ComponentConfiguration.ungetService(ComponentConfiguration.java:537)
	at org.knopflerfish.framework.PermissionOps.callUngetService(PermissionOps.java:370)
	at org.knopflerfish.framework.ServiceRegistrationImpl.ungetService(ServiceRegistrationImpl.java:551)
	at org.knopflerfish.framework.ServiceReferenceImpl.ungetService(ServiceReferenceImpl.java:220)
	at org.knopflerfish.framework.BundleContextImpl.ungetService(BundleContextImpl.java:406)
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.delegateAddService(ResourceTracker.java:48)
	at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:40)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:901)
	at org.knopflerfish.framework.Listeners.serviceChanged(Listeners.java:430)
	at org.knopflerfish.framework.PermissionOps.callServiceChanged(PermissionOps.java:340)

**Comment by janste63** [comment]
Problem was that when a delayed components service was returned but the component still satisfied, then there was a faulty re-registering of the components service. Fixed in component version 6.0.1.
