### ISSUE TITLE
ConditionalPermissionAdminTestSuite fails with Oracle JDK 1.8.0_77-b03

### ISSUE THREAD

**Issue by janste63** [knopflerfish/knopflerfish.org#2]
After installing the new Oracle JDK (build 1.8.0_77-b03) on MacOS 10.11.4, the following three test
Condperm210a, Condperm220a and Condperm230a in the ConditionalPermissionAdminTestSuite fails.

```
Failure: Condperm210a - P3 not exporting bundle, BundleImpl[id=140] != BundleImpl[id=142] :CONDPERM210A:FAIL
junit.framework.AssertionFailedError: P3 not exporting bundle, BundleImpl[id=140] != BundleImpl[id=142] :CONDPERM210A:FAIL
 at junit.framework.Assert.fail(Assert.java:47)
 at org.knopflerfish.bundle.condpermadmin_test.CondPermAdminTestSuite$Condperm210a.runTest(CondPermAdminTestSuite.java:618)
 at junit.framework.TestCase.runBare(TestCase.java:127)
 at junit.framework.TestResult$1.protect(TestResult.java:106)
 at junit.framework.TestResult.runProtected(TestResult.java:124)
 at junit.framework.TestResult.run(TestResult.java:109)
 at junit.framework.TestCase.run(TestCase.java:118)
 at junit.framework.TestSuite.runTest(TestSuite.java:208)
 at junit.framework.TestSuite.run(TestSuite.java:203)
 at org.knopflerfish.bundle.junit.JUnitServiceImpl.runTestCase(JUnitServiceImpl.java:177)
 at org.knopflerfish.bundle.junit.JUnitServiceImpl.runTestXML(JUnitServiceImpl.java:82)
 at org.knopflerfish.bundle.junit.JUnitServiceImpl.runTest(JUnitServiceImpl.java:62)
 at org.knopflerfish.bundle.junit_runner.Grunt.doRun(Grunt.java:198)
 at org.knopflerfish.bundle.junit_runner.Grunt.doGrunt(Grunt.java:79)
 at org.knopflerfish.bundle.junit_runner.Activator.start(Activator.java:57)
 at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:387)
 at org.knopflerfish.framework.BundleThread.run(BundleThread.java:145)

Failure: Condperm220a - started test bundleP4! :CONDPERM220A:FAIL
junit.framework.AssertionFailedError: started test bundleP4! :CONDPERM220A:FAIL
 at junit.framework.Assert.fail(Assert.java:47)
 at org.knopflerfish.bundle.condpermadmin_test.CondPermAdminTestSuite$Condperm220a.runTest(CondPermAdminTestSuite.java:703)
 at junit.framework.TestCase.runBare(TestCase.java:127)
 at junit.framework.TestResult$1.protect(TestResult.java:106)
 at junit.framework.TestResult.runProtected(TestResult.java:124)
 at junit.framework.TestResult.run(TestResult.java:109)
 at junit.framework.TestCase.run(TestCase.java:118)
 at junit.framework.TestSuite.runTest(TestSuite.java:208)
 at junit.framework.TestSuite.run(TestSuite.java:203)
 at org.knopflerfish.bundle.junit.JUnitServiceImpl.runTestCase(JUnitServiceImpl.java:177)
 at org.knopflerfish.bundle.junit.JUnitServiceImpl.runTestXML(JUnitServiceImpl.java:82)
 at org.knopflerfish.bundle.junit.JUnitServiceImpl.runTest(JUnitServiceImpl.java:62)
 at org.knopflerfish.bundle.junit_runner.Grunt.doRun(Grunt.java:198)
 at org.knopflerfish.bundle.junit_runner.Grunt.doGrunt(Grunt.java:79)
 at org.knopflerfish.bundle.junit_runner.Activator.start(Activator.java:57)
 at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:387)
 at org.knopflerfish.framework.BundleThread.run(BundleThread.java:145)

Failure: Condperm230a - started test bundleP5! :CONDPERM230A:FAIL
junit.framework.AssertionFailedError: started test bundleP5! :CONDPERM230A:FAIL
 at junit.framework.Assert.fail(Assert.java:47)
 at org.knopflerfish.bundle.condpermadmin_test.CondPermAdminTestSuite$Condperm230a.runTest(CondPermAdminTestSuite.java:795)
 at junit.framework.TestCase.runBare(TestCase.java:127)
 at junit.framework.TestResult$1.protect(TestResult.java:106)
 at junit.framework.TestResult.runProtected(TestResult.java:124)
 at junit.framework.TestResult.run(TestResult.java:109)
 at junit.framework.TestCase.run(TestCase.java:118)
 at junit.framework.TestSuite.runTest(TestSuite.java:208)
 at junit.framework.TestSuite.run(TestSuite.java:203)
 at org.knopflerfish.bundle.junit.JUnitServiceImpl.runTestCase(JUnitServiceImpl.java:177)
 at org.knopflerfish.bundle.junit.JUnitServiceImpl.runTestXML(JUnitServiceImpl.java:82)
 at org.knopflerfish.bundle.junit.JUnitServiceImpl.runTest(JUnitServiceImpl.java:62)
 at org.knopflerfish.bundle.junit_runner.Grunt.doRun(Grunt.java:198)
 at org.knopflerfish.bundle.junit_runner.Grunt.doGrunt(Grunt.java:79)
 at org.knopflerfish.bundle.junit_runner.Activator.start(Activator.java:57)
 at org.knopflerfish.framework.BundleImpl.start0(BundleImpl.java:387)
 at org.knopflerfish.framework.BundleThread.run(BundleThread.java:145)

```

This was tested with [the framework 7.2.3 commit](https://github.com/knopflerfish/knopflerfish.org/commit/ff725ef6d61f260afb0130ad3fdd97721969c535).
But the problem was also there in the previous version.

**Comment by janste63** [comment]
Still valid for 1.8.0_91-b14.

**Comment by janste63** [comment]
The reason for this was that JDK 1.8.0_77 default configuration deemed the key lengths in the test cases too short to bee secure. An increase to 2048 bits fixed the problem.
