### ISSUE TITLE
Desktop bundle uses no longer supported com.apple.eawt classes

### ISSUE THREAD

**Issue by chlarsson** [knopflerfish/knopflerfish.org#33]
Sep 22 16:44:56 WARNING #25 Desktop        - This version of Mac OS X does not support the Apple EAWT.  Application quit handling has been disabled (java.lang.ClassNotFoundException: com.apple.eawt.QuitHandler)
java.lang.ClassNotFoundException: com.apple.eawt.QuitHandler
	at org.knopflerfish.framework.BundleClassLoader.findClass(BundleClassLoader.java:176)
	at org.knopflerfish.framework.BundleClassLoader.loadClass(BundleClassLoader.java:305)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:292)
	at org.knopflerfish.bundle.desktop.swing.OSXAdapter.setQuitHandler(OSXAdapter.java:130)
	at org.knopflerfish.bundle.desktop.swing.Desktop.start(Desktop.java:357)
	at org.knopflerfish.bundle.desktop.swing.Activator.openDesktop(Activator.java:381)
	at org.knopflerfish.bundle.desktop.swing.Activator$3.run(Activator.java:367)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Sep 22 16:44:56 WARNING #25 Desktop        - This version of Mac OS X does not support the Apple EAWT.  Application about handling has been disabled (java.lang.ClassNotFoundException: com.apple.eawt.AboutHandler)
java.lang.ClassNotFoundException: com.apple.eawt.AboutHandler
	at org.knopflerfish.framework.BundleClassLoader.findClass(BundleClassLoader.java:176)
	at org.knopflerfish.framework.BundleClassLoader.loadClass(BundleClassLoader.java:305)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:292)
	at org.knopflerfish.bundle.desktop.swing.OSXAdapter.setAboutHandler(OSXAdapter.java:170)
	at org.knopflerfish.bundle.desktop.swing.Desktop.start(Desktop.java:361)
	at org.knopflerfish.bundle.desktop.swing.Activator.openDesktop(Activator.java:381)
	at org.knopflerfish.bundle.desktop.swing.Activator$3.run(Activator.java:367)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by chlarsson** [comment]
More info on the issue here:
https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-97C1D0BB-D5D3-4CAD-B17D-03A87A0AAF3B

and here:
http://openjdk.java.net/jeps/272
