### ISSUE TITLE
knopflerfish does not work for freeplane any more

### ISSUE THREAD

**Issue by fnatter** [knopflerfish/knopflerfish.org#4]
Dear knopflerfish devs,

the freeplane project [1] uses knopflerfish for OSGi support for years.
Freeplane is somewhat special in that it loads _extracted_ OSGi "jars":

felix@debianunstable:/$ find /usr/share/freeplane/core/org.freeplane.core/
/usr/share/freeplane/core/org.freeplane.core/
/usr/share/freeplane/core/org.freeplane.core/lib
/usr/share/freeplane/core/org.freeplane.core/lib/freeplaneeditor-1.5.jar
/usr/share/freeplane/core/org.freeplane.core/lib/jortho-1.5.jar
/usr/share/freeplane/core/org.freeplane.core/lib/freeplaneviewer.jar
/usr/share/freeplane/core/org.freeplane.core/lib/freeplaneosgi-1.5.jar
/usr/share/freeplane/core/org.freeplane.core/META-INF
/usr/share/freeplane/core/org.freeplane.core/META-INF/MANIFEST.MF

With knopflerfish 5.2.0, there is a problem when loading/starting the core bundle:
felix@debianunstable:~$ freeplane
org.knopflerfish.framework.readonly=true
org.knopflerfish.gosg.jars=reference:file:/usr/share/freeplane/core/
org.freeplane.basedirectory=/usr/share/freeplane
java.security.policy=/usr/share/freeplane/freeplane.policy
org.osgi.framework.storage=/usr/share/freeplane/fwdir
Knopflerfish OSGi framework launcher, version <unknown>
Copyright 2003-2016 Knopflerfish. All Rights Reserved.
See http://www.knopflerfish.org for more information.

java.lang.IllegalArgumentException: Failed to read exports: java.io.FileNotFoundException: /home/felix/exports (No such file or directory)
    at org.knopflerfish.framework.SystemBundle.addSysPackagesFromFile(SystemBundle.java:699)
    at org.knopflerfish.framework.SystemBundle.initSystemBundle(SystemBundle.java:557)
    at org.knopflerfish.framework.FrameworkContext.init(FrameworkContext.java:402)
    at org.knopflerfish.framework.SystemBundle.doInit(SystemBundle.java:622)
    at org.knopflerfish.framework.SystemBundle.init(SystemBundle.java:152)
    at org.knopflerfish.framework.Main.assertFramework(Main.java:446)
    at org.knopflerfish.framework.Main.handleArgs(Main.java:546)
    at org.knopflerfish.framework.Main.start(Main.java:224)
    at org.knopflerfish.framework.Main.main(Main.java:156)
    at org.freeplane.launcher.Launcher.run(Launcher.java:115)
    at org.freeplane.launcher.Launcher.launch(Launcher.java:80)
    at org.freeplane.launcher.Launcher.main(Launcher.java:67)
Error: Command "-istart org.freeplane.core" failed, Failed to read exports: java.io.FileNotFoundException: /home/felix/exports (No such file or directory)

Could you please help me find a solution or workaround?

[1] https://github.com/freeplane/freeplane

Many Thanks and Best Regards,
Felix

**Comment by chlarsson** [comment]
Hi, 
from the stack trace it seems like there is a file missing called: exports

It's normally located inside the framework.jar, in the root folder of the jar file. 

I assume you also use an "extracted" framework. Is the file present in the extracted framework's root folder?

Thanks,
Christer

**Comment by fnatter** [comment]
hello Christer,

it is indeed a missing exports node in the framework jar, due to a packaging error.

Thanks for the hint and Best Regards,
Felix

**Comment by chlarsson** [comment]
Good to hear.

Thanks,
Christer
