### ISSUE TITLE
SCR gets ConcurrentModificationException in service listener

### ISSUE THREAD

**Issue by janste63** [knopflerfish/knopflerfish.org#53]
## DEBUG: errors - FrameworkErrorEvent throwable:
java.util.ConcurrentModificationException
                at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442)
                at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
                at org.knopflerfish.bundle.component.ComponentServiceListener.serviceChanged(ComponentServiceListener.java:70)
                at org.knopflerfish.framework.Listeners.serviceChanged(Listeners.java:430)
                at org.knopflerfish.framework.PermissionOps.callServiceChanged(PermissionOps.java:340)
                at org.knopflerfish.framework.Services.register(Services.java:179)
                at org.knopflerfish.framework.BundleContextImpl.registerService(BundleContextImpl.java:289)
                at org.knopflerfish.framework.BundleContextImpl.registerService(BundleContextImpl.java:304)

**Comment by chlarsson** [comment]
Issue corrected in Component (SCR) 6.0.7 and released in KF 6.1.5
